### ISSUE TITLE
Fix composer.json for Contao 4.4 LTS

### ISSUE THREAD

**Issue by havutcuoglu** [dklemmt/contao_dk_caroufredsel#29]
The `composer.json` file has as require the` "contao/core-bundle": "~3.2",`

Please change the require to `"contao/core-bundle": "~3.2 || ~4.0",` for Contao 4.4 LTS

The Caroufredsel from the [https://github.com/mindbird/contao_dk_caroufredsel](url) works fine with Contao 4.4 LTS.

Only problem here is the issue [https://github.com/mindbird/contao_dk_caroufredsel/issues/7](url). If I fix the autoload file, I can use the repository without any problems.

Thanks a lot

**Comment by fritzmg** [comment]
Please provide a PR with the necessary changes.

**Comment by havutcuoglu** [comment]
You will get it ASAP.

**Comment by havutcuoglu** [comment]
I was able to install the repository in C 4.9.13
